version: '3'

services:
  node-app:
    build: .  # This will build the image from the Dockerfile in the current directory
    container_name: node-app-container
    labels:
      - "nginx.domain=node-app.example.com"
    ports:
      - "3000:3000"

  nginx:
    image: nginx
    container_name: nginx-container
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
