name: Build and Deploy Node.js App with Docker

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx (for building Docker images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Log in to Docker Hub (Replace with your Docker Hub credentials)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Verify installation

    # Step 5: Build and push Docker images
    - name: Build and push Docker images
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Make sure the build job completes first

    steps:
    # Step 1: Checkout the repository again for deployment tasks
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up SSH for deployment (e.g., to a remote server)
    - name: Set up SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "Nice Job!!!"
          cd nodejs-app
          # Stop and remove all running containers
          echo "Stopping and removing all containers..."
          docker stop $(docker ps -aq) || true
          docker rm $(docker ps -aq) || true
          echo "Starting Docker containers with Docker Compose..."
          docker-compose up -d
          echo "Deployment complete!"
          

        
          
          
