name: Build and Deploy Node.js App with Docker

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository again for deployment tasks
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up SSH for deployment (e.g., to a remote EC2 server)
    - name: Set up SSH and deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}  # EC2 public IP or DNS name
        username: ${{ secrets.SSH_USER }}  # SSH user (e.g., 'ubuntu')
        key: ${{ secrets.KEY }}  # SSH private key (ensure it's base64 encoded if required)
        port: ${{ secrets.SSH_PORT }}  # Default is 22 for EC2 instances
        script: |
          echo "SSH into EC2 Instance Successful"
          
          # Navigate to the project directory on the EC2 instance
          cd nodejs-app  # Update with the correct path to your app on the EC2

          # Stop and remove all running containers
          echo "Stopping and removing all containers..."
          docker stop $(docker ps -aq) || true
          docker rm $(docker ps -aq) || true

          # Start the Docker containers using Docker Compose
          echo "Starting Docker containers with Docker Compose..."
          docker-compose up -d

          echo "Deployment complete!"
